version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Khoa2401_
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Khoa2401_
      DB_NAME: todo_db
      DB_PORT: 5432
      JWT_SECRET: supersecretkey
      PORT: 8080
    # volumes:
    #   - .:/app

volumes:
  pgdata:
